### ISSUE TITLE
Removal of footer text with link

### ISSUE THREAD

**Issue by Hybrol** [HaileyBot/captcha-generator#2]
By any chance the footer text can be removed?

**Comment by cheesits456** [comment]
The text at the bottom of the image actually serves two purposes - first the obvious; leading people to the open source repository so other people can use it in their own projects, but the actual reason I added that text is that it does a really good job confusing "image to text" programs, because they see the plain text at the bottom and think that's what you want :P I have nothing against people forking this repo and removing the text, (as long as proper attribution is given in some other form), but imo it's a good idea to have _something_ there at the bottom - something that confuses software, but that humans can easily tell isn't part of the captcha. Just my thoughts though, it's free and open source software so of course you're free to do what you want with it, within the boundaries of the license, of course <3

**Comment by Hybrol** [comment]
Thanks Quinn! I might fork it but ofc all credits will always be given to
original owner! I never thought of that since I'm no image analist expert

A quinta, 29/10/2020, 20:37, Quin <notifications@github.com> escreveu:

**Comment by cheesits456** [comment]
Just realized my response didn't actually provide a solution to this issue's title, oops :P

The specific lines of code relating to the bottomtext are these ones:
https://github.com/HaileyBot/captcha-generator/blob/master/src/index.ts#L125-L136

After editing, you'll need to compile it to JS. 

First, make sure the dev dependencies are installed by executing:

```bash
npm i --only=dev`
```

Then from the project's root folder, run the TypeScript compiler:

```bash
./node_modules/typescript/bin/tsc
```

Or if you have TypeScript installed globally, you can just do:

```bash
tsc
```

_I should probably include this stuff in the `README` :thinking:_
